print("Welcome to the Lost Treasure Game!")
UserName = input("Please enter your name: ")
print("Hello", UserName, "! Your adventure begins now.")
UserAge = int(input("Please enter your age: "))
print("Great! You are", UserAge, "years old.")
print("You find yourself in a mysterious forest. There are other questions I would Like to Ask you.")
FavColor = input("What is your favourite colour? ")
FavAnimal = input("What is your favourite animal? ")
print("Interesting! Your favourite colour is", FavColor, "and your favourite animal is", FavAnimal, ".")
print("Now Your Pirate Name is", FavColor, FavAnimal, "!")
